language: node_js
sudo: false
node_js:
  - '4.5.0'
  - '5.6'
  - '6.4'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-veams' ]; then cd .. && eval "mv $currentfolder generator-veams" && cd generator-veams; fi

git:
  submodules: false
# whitelist
branches:
  only:
    - master